create table if not exists public.genre_options (
  id bigint generated by default as identity primary key,
  name text not null unique check (btrim(name) <> ''),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.genre_options
  add column if not exists is_active boolean not null default true;

insert into public.genre_options (name)
values
  ('Action'),
  ('Comedy'),
  ('Drama'),
  ('Horror'),
  ('Science Fiction'),
  ('Romance'),
  ('Thriller'),
  ('Epic'),
  ('Spy'),
  ('psychological thriller'),
  ('Fantasy'),
  ('Adventure'),
  ('Superhero'),
  ('MCU'),
  ('Dark comedy'),
  ('Crime')
on conflict (name) do nothing;

insert into public.genre_options (name)
select distinct btrim(option_name)
from (
  select unnest(genres) as option_name
  from public.movies
  union all
  select unnest(string_to_array(genre, ',')) as option_name
  from public.movies
) existing_genres
where btrim(option_name) <> ''
on conflict (name) do nothing;

alter table public.genre_options enable row level security;

drop policy if exists "Anyone can view genre options" on public.genre_options;
create policy "Anyone can view genre options"
  on public.genre_options for select
  to anon, authenticated
  using (is_active = true or public.is_admin());

drop policy if exists "Admins can insert genre options" on public.genre_options;
create policy "Admins can insert genre options"
  on public.genre_options for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update genre options" on public.genre_options;
create policy "Admins can update genre options"
  on public.genre_options for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete genre options" on public.genre_options;
create policy "Admins can delete genre options"
  on public.genre_options for delete
  to authenticated
  using (public.is_admin());

grant select on public.genre_options to anon, authenticated;
grant insert, update, delete on public.genre_options to authenticated;
grant usage, select on sequence public.genre_options_id_seq to authenticated;
