create table if not exists public.hero_movies (
  id bigint generated by default as identity primary key,
  movie_id bigint not null unique references public.movies(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.hero_movies enable row level security;

drop policy if exists "Anyone can view hero movies" on public.hero_movies;
create policy "Anyone can view hero movies"
  on public.hero_movies for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can insert hero movies" on public.hero_movies;
create policy "Admins can insert hero movies"
  on public.hero_movies for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update hero movies" on public.hero_movies;
create policy "Admins can update hero movies"
  on public.hero_movies for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete hero movies" on public.hero_movies;
create policy "Admins can delete hero movies"
  on public.hero_movies for delete
  to authenticated
  using (public.is_admin());

create index if not exists hero_movies_position_idx on public.hero_movies (position);

grant select on public.hero_movies to anon, authenticated;
grant insert, update, delete on public.hero_movies to authenticated;

do $$
declare
  hero_sequence text;
begin
  hero_sequence := pg_get_serial_sequence('public.hero_movies', 'id');
  if hero_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', hero_sequence);
  end if;
end;
$$;